### ISSUE TITLE
Full video from Kubecon?

### ISSUE THREAD

**Issue by jasondewitt** [carsonoid/kube-decon#1]
Hey Carson

I really enjoyed this talk at Kubecon, I hate that you only got 30 minutes and had to rush. Did that full video you recorded ever get released? I'd love to watch it and share with my coworkers.

**Comment by carsonoid** [comment]
I'm glad you enjoyed it!

Here is the link: https://vimeo.com/245778144/4d1d597c5e

I also added a readme to the repo with the link.
